name: Build, analyze and test

on:
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [25]
#        api-level: [25, 26, 28, 30]
        target: [default]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          working-directory: ./example
          script: flutter test integration_test
